config/routes.rb
Medinst::Application.routes.draw do

  get "newspaper/index"

  get "albums/index"

  get "albums/show"

  match '/news' => 'news#index'
  match '/albums' => 'albums#index'
  match '/newspaper' => 'newspaper#index'
  devise_for :users
  devise_for :users, :path => "users",
             :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret',
                              :confirmation => 'verification', :unlock => 'unblock',
                              :registration => 'register', :sign_up => 'signup' }

  resource :news
  resources :pages
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => 'pages#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :content, :title
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :role
  validates_presence_of :email, :username, :password, :password_confirmation
end

app/controllers/albums_controller.rb
# encoding: utf-8

class AlbumsController < ApplicationController
  def index
    @sub_title = "Альбомы"
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def authenticate_active_admin_user!
    authenticate_user!
    if current_user.role != 2
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end
end

app/controllers/news_controller.rb
# encoding: utf-8

class NewsController < ApplicationController
  def index
    @sub_title = "Новости"
    @news = News.all
  end
end

app/controllers/newspaper_controller.rb
# encoding: utf-8

class NewspaperController < ApplicationController
  def index
    @sub_title = "Газета"
  end
end

app/controllers/pages_controller.rb
# encoding: utf-8

class PagesController < ApplicationController
  def index
    @sub_title = "Главная страница"
  end

  def show
    @page = Page.find_by_id(params[:id])
    @sub_title = @page.title
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/newspaper_helper.rb
module NewspaperHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/albums/index.html.haml
%h1 Albums#index
%p Find me in app/views/albums/index.html.haml

app/views/albums/show.html.haml
%h1 Albums#show
%p Find me in app/views/albums/show.html.haml

app/views/layouts/application.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title
      = "Медицинский институт"
      - if @sub_title
        = " | " + @sub_title
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    = current_user.role if current_user
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="/") Медицинский Институт
          .container.nav-collapse
            %ul.nav.nav-tabs
              %li.active= link_to "Новости", news_path
              %li= link_to "Газета", newspaper_path
              %li.dropdown
                = link_to "Студсовет<b class='caret'></b>".html_safe, "#", id: "drop1", role: "button", class: "dropdown-toggle", "data-toggle" => "dropdown"
                %ul.dropdown-menu(role="menu" aria-labelledby="drop1")
                  %li= link_to "fgfgdf", "#"
                  %li= link_to "fgfgdf", "#"
                  %li= link_to "fgfgdf", "#"
              %li= link_to "Форум", "#"
              %li= link_to "Полезное", "#"
              %li= link_to "Вопросы", "#"
              %li= link_to "Альбомы", albums_path
              - if current_user
                %li= link_to "Выйти (#{current_user.username})", destroy_user_session_path, :method => :delete
              - else
                %li= link_to "Войти", new_user_session_path
                %li= link_to "Регистрация", new_user_registration_path


    .container

      .content
        .row
          .span9
            = bootstrap_flash
            = yield
          .span3
            .well.sidebar-nav
              %h3 Sidebar
              %ul.nav.nav-list
                %li.nav-header Sidebar
                %li= link_to "Link 1", "/path1"
                %li= link_to "Link 2", "/path2"
                %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Crailway Studios 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/news/index.haml
%h1 Новости
- @news.each do |news|
  %h1
    = news.title
  %p
    = news.content

app/views/newspaper/index.html.haml
%h1 Newspaper#index
%p Find me in app/views/newspaper/index.html.haml

app/views/pages/index.haml
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p><p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/show.haml
%h1
  = @page.title
%p
  = @page.content.html_safe

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>